# This workflow will build a package using Maven

name: Maven Package

# When to build
on:
  push:
      branches: [ "master" ]

jobs:
  analyze:
        name: Analyze
        runs-on: ubuntu-latest

        strategy:
          fail-fast: false
          matrix:
            language: [ 'java' ]

        steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Inizialize code
          uses: github/codeql-action/init@v1
          with:
            languages: ${{ matrix.language }}

        - name: Autobuild
          uses: github/codeql-action/autobuild@v1

        - name: Perform Code Analysis
          uses: github/codeql-action/analyze@v1

  build:
    # The type of computer where it works
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Set up JDK 11
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    # Build with Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
